args <- commandArgs(trailingOnly=TRUE)
stopifnot(length(args)==2)
for (pkg in c('jsonlite','variancePartition','edgeR','limma','BiocParallel')) if (!requireNamespace(pkg,quietly=TRUE)) stop(paste('Missing existing server package',pkg))
config <- jsonlite::fromJSON(args[[1]]);folder <- args[[2]]
if (dir.exists(folder)) stop('Choose a fresh output directory')
y <- as.matrix(read.csv(config$counts,row.names=1,check.names=FALSE))
meta <- read.csv(config$metadata,row.names=1,check.names=FALSE)
stopifnot(setequal(colnames(y),rownames(meta)),!anyNA(y),!anyNA(meta),all(is.finite(y)),all(y>=0),all(y==round(y)))
meta <- meta[colnames(y),,drop=FALSE]
# Formula and contrast are trusted analysis specifications read only on the owned server.
if (!is.character(config$formula) || !grepl('^[~A-Za-z0-9_ .+*():|]+$',config$formula)) stop('Invalid restricted formula')
if (grepl('[A-Za-z_][A-Za-z0-9_.]* *[(]',config$formula)) stop('Function calls are not allowed in the model specification')
form <- as.formula(config$formula)
variables <- all.vars(form)
stopifnot(all(variables %in% names(meta)),config$unit_key %in% names(meta),length(unique(meta[[config$unit_key]]))>=10)
if (!is.null(config$categorical)) for (key in config$categorical) meta[[key]] <- factor(meta[[key]])
fixed <- lme4::nobars(form)
design <- model.matrix(fixed,meta)
if (qr(design)$rank<ncol(design) || nrow(design)-ncol(design)<3) stop('Confounded or saturated fixed design')
if (any(colSums(y)==0) || sum(rowSums(y>=10)>=3)<20) stop('Count QC failed')
dir.create(folder,recursive=TRUE)
write.csv(design,file.path(folder,'design_matrix.csv'))
dge <- edgeR::calcNormFactors(edgeR::DGEList(y[rowSums(y>=10)>=3,,drop=FALSE]))
param <- BiocParallel::SnowParam(workers=min(4L,max(1L,as.integer(config$threads))))
v <- variancePartition::voomWithDreamWeights(dge,form,meta,BPPARAM=param)
if (!is.character(config$contrast) || !grepl('^[A-Za-z0-9_ .+*/()-]+$',config$contrast)) stop('Invalid restricted contrast')
if (grepl('[A-Za-z_][A-Za-z0-9_.]* *[(]',config$contrast)) stop('Function calls are not allowed in contrasts')
contrast <- variancePartition::makeContrastsDream(form,meta,contrasts=c(primary=config$contrast))
fit <- variancePartition::dream(v,form,meta,contrast,BPPARAM=param)
fit <- limma::eBayes(fit)
tab <- limma::topTable(fit,coef=1,number=Inf,sort.by='none')
write.csv(tab,file.path(folder,'differential_expression.csv'))
write.csv(v$E,file.path(folder,'voom_expression.csv'))
writeLines(paste('variancePartition',utils::packageVersion('variancePartition')),file.path(folder,'backend_version.txt'))
saveRDS(fit,file.path(folder,'dream_fit.rds'))
