args <- commandArgs(trailingOnly=TRUE)
stopifnot(length(args)==2)
if (!requireNamespace('jsonlite',quietly=TRUE) || !requireNamespace('tximport',quietly=TRUE)) stop('Existing jsonlite and tximport are required')
config <- jsonlite::fromJSON(args[[1]])
folder <- args[[2]]
if (dir.exists(folder)) stop('Choose a fresh output directory')
files <- setNames(config$files$path,config$files$sample)
stopifnot(length(files)>=3,!anyDuplicated(names(files)),all(file.exists(files)))
mapping <- read.csv(config$tx2gene,stringsAsFactors=FALSE,check.names=FALSE)
stopifnot(all(c('transcript','gene') %in% colnames(mapping)),!anyDuplicated(mapping$transcript),!anyNA(mapping),all(nzchar(mapping$transcript)),all(nzchar(mapping$gene)))
txi <- tximport::tximport(files,type='salmon',tx2gene=mapping[,c('transcript','gene')],countsFromAbundance='no')
dir.create(folder,recursive=TRUE)
saveRDS(txi,file.path(folder,'tximport.rds'))
write.csv(txi$counts,file.path(folder,'estimated_counts.csv'))
write.csv(txi$length,file.path(folder,'effective_lengths.csv'))
write.csv(txi$abundance,file.path(folder,'abundance.csv'))
writeLines(paste('tximport',utils::packageVersion('tximport')),file.path(folder,'backend_version.txt'))
writeLines('Estimated counts must enter a tximport-aware DESeq2/edgeR analysis with effective lengths; do not round and feed arbitrary counts-only models.',file.path(folder,'limitations.txt'))
